### ISSUE TITLE
URLs for `term-to-gene` and `gene-to-term` can easily become too long

### ISSUE THREAD

**Issue by thevulch** [Planteome/planteome-data-visualization#14]
Two solutions:

- Paginate requests to guarantee a valid URL length
  - **BIG** issues with integrating all the queries together - there'll be overlapping results which we'd have to work through
- Change the endpoints to be POST instead of GET
  - Needs server change

**Comment by thevulch** [comment]
@elserj hope you can convince the server guy to help us out!

**Comment by elserj** [comment]
Fixed in Planteome/amigo@12c536bd438436052f673cbf0e45aaa517d122bc

Updated both dev.planteome.org and test.planteome.org.

**Comment by thevulch** [comment]
Don't want to re-open this, but Is [this line](https://github.com/Planteome/amigo/blob/8262297ac19cb1b4d8695cc32367923dab3de880/bin/amigo.js#L800) a typo? Both for `term-to-gene` and `gene-to-term` amigo creates a `gene-to-term` envelope.
