### ISSUE TITLE
error 413 Request entity too large

### ISSUE THREAD

**Issue by qubotong** [Planteome/planteome-data-visualization#19]
Hi @elserj 

Please get the newest version of codes from github viz branch. Also, I test 200 and 300 input genes and get a error 413 Request entity too large. I googled and people say this is caused by the server setting as following:

http://cnedelcu.blogspot.com/2013/09/nginx-error-413-request-entity-too-large.html 
Could you have a look to see if we can make the maximum upload bigger.

**Comment by elserj** [comment]
That link is for nginx, we are using Apache.  I'm still looking to see if I can find the correct setting for this.  Are you sending the POST in headers or body?  The corresponding changes to Apache differ.

**Comment by qubotong** [comment]
@thevulch We are sending them in body, right? I'm not sure about it because all the js files areincluded in the headers, but the requests are triggered in the body. @elserj you are talking about the html header or body, right?

**Comment by elserj** [comment]
Well, I think I changed it for both, so can you retry and let me know if it still has issue?

**Comment by qubotong** [comment]
@elserj how big did you change it to? I still have that problem when inputting 200 genes.

**Comment by elserj** [comment]
Unlimited, so I guess I didn't do it correctly, or it is something else.  The logs are being filled with lots of useless info, so it's hard to track down exactly what is causing the error.  Can you send me an email with the list of genes you are sending, or the URL you are sending?

**Comment by elserj** [comment]
Pretty sure this was fixed in Planteome/amigo@fac87a72105f648bf8cb8e59a9b72592f546e8e4

Closing for now.  Reopen if this isn't fixed.
