### ISSUE TITLE
Down load button

### ISSUE THREAD

**Issue by qubotong** [Planteome/planteome-data-visualization#26]
for users to download the analysis results

**Comment by thevulch** [comment]
is there any specific format for this?

**Comment by qubotong** [comment]
I think we could just save it as txt file for temporary use.

**Comment by thevulch** [comment]
I mean, what data and format is the data in the text file?

Is it just saving every value of each row in the table? Does it include data about input? Is each column split up by a delimiter (and what is it)? Do we include headers? Does anything about the network/visualisation go in the file? etc.

**Comment by qubotong** [comment]
@elserj When we allow the users to download the analysis results, is there any specific formats we need to follow? Or we can just output our results by saving the whole table in the txt file with using tab stop character as the delimiter. We can design a header to show this is a static results from our website and some other things.

**Comment by elserj** [comment]
tab delimited with the whole table would be correct.  Header would also be a good idea.

**Comment by qubotong** [comment]
The download button is added.
commit 448687913624bf29dff6203da1e12f0d5550b463
